package gov.raleighnc.switchyard.integration.service.cwmeter;

import gov.raleighnc.switchyard.integration.domain.Result;
import gov.raleighnc.switchyard.integration.domain.ccb.CcbCwWorkOrder;

/**
 * A Switchyard "Composite Service" consisting of Cityworks Meter-related services usable by the outside world.
 * 
 * @author mikev
 *
 */
public interface CwMeterService {
	/**
	 * Creates a new work order in the Cityworks system and returns either the Citywork's work order id (numeric)
	 * or an error message as a Result.
	 * 
	 * @param workorder The WorkOrder to persist.  The WorkOrder's workorderid field is not used even if populated since
	 *                  one will be generated by Cityworks.       
	 * @return The result of the WorkOrder creation
	 */	
	Result createWorkOrder(CcbCwWorkOrder workorder);
	
	/**
	 * Updates and existing work order in the Cityworks system and returns either the Citywork's work order id (numeric)
	 * or an error message as a Result.
	 * 
	 * @param workorder The WorkOrder to update      
	 * @return The result of the WorkOrder update
	 */		
	Result updateWorkOrder(CcbCwWorkOrder workorder);
	
	/**
	 * Updates the meter information only and ignores any WorkOrder information
	 * 
	 * @param workorder The Meter part of the WorkOrder to update
	 * @return The result of the Meter update
	 */
	Result updateMeter(CcbCwWorkOrder workorder);
}